[platformio]
src_dir = ./

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

build_flags =
    -I include
    -I include/hal
    -I include/sx1276
    -I ../vendor/sx127x
    -I ../vendor/U8g2_Arduino/src/clib
    -Wall -Wextra -O2
    -DUSE_SX1276_RADIO

build_src_filter =
    +<src/main.c>
    +<src/hal/*.c>
    +<src/sx1276/*.c>
    +<../vendor/sx127x/*.c>
    +<../vendor/U8g2_Arduino/src/clib/*.c>

upload_protocol = cmsis-dap
debug_tool = cmsis-dap
monitor_speed = 115200
